<a href="https://colab.research.google.com/github/LCaravaggio/AnalisisPredictivo/blob/master/03_Regresi%C3%B3n_Lineal/Regresi%C3%B3n_lineal_multiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importar librerías

In [1]:
from sklearn import datasets, linear_model

Cargar datos

In [2]:
boston = datasets.load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

Un poco de EDA

In [3]:
print('Información en el dataset:')
print(boston.keys())
print()

Información en el dataset:
dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])



In [4]:
print('Características del dataset:')
print(boston.DESCR)

Características del dataset:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per 

In [5]:
print('Cantidad de datos:')
print(boston.data.shape)
print()

Cantidad de datos:
(506, 13)



In [6]:
print('Nombres columnas:')
print(boston.feature_names)

Nombres columnas:
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


Preparar la regresión lineal

In [31]:
X_multiple = boston.data[:, 5:8]
print(X_multiple)

[[ 6.575  65.2     4.09  ]
 [ 6.421  78.9     4.9671]
 [ 7.185  61.1     4.9671]
 ...
 [ 6.976  91.      2.1675]
 [ 6.794  89.3     2.3889]
 [ 6.03   80.8     2.505 ]]


Defino los datos correspondientes a las etiquetas


In [13]:
y_multiple = boston.target

Regresión Lineal Múltiple

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_multiple, y_multiple, test_size=0.2)
lr_multiple = linear_model.LinearRegression()
lr_multiple.fit(X_train, y_train)

LinearRegression()

Predicción

In [22]:
Y_pred_multiple = lr_multiple.predict(X_test)
print('DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE')
print()
print('Valor de las pendientes o coeficientes "a":')
print(lr_multiple.coef_)
print('Valor de la intersección o coeficiente "b":')
print(lr_multiple.intercept_)
print('Precisión del modelo:')
print(lr_multiple.score(X_train, y_train))

DATOS DEL MODELO REGRESIÓN LINEAL MULTIPLE

Valor de las pendientes o coeficientes "a":
[ 8.53782222 -0.06748831]
Valor de la intersección o coeficiente "b":
-26.335515809459842
Precisión del modelo:
0.530638752433958


In [23]:
print(lr_multiple.score(X_test, y_test))

0.5243581372138428


Statsmodel

In [27]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [45]:
x1=boston.data[:, 5:6]
x2=boston.data[:, 6:7]
x3=boston.data[:, 7:8]
y=boston.target

In [56]:
df = {'x1': x1, 'x2': x2, 'x3': x3, 'y': y}

formula = 'y ~ x1 + x2 + x3'

lm = smf.ols(formula=formula, data=df).fit()
print(lm.params)

lm.rsquared

Intercept   -21.872788
x1            8.440629
x2           -0.099418
x3           -0.480384
dtype: float64


0.5355978698785334

In [57]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.536
Model:                            OLS   Adj. R-squared:                  0.533
Method:                 Least Squares   F-statistic:                     193.0
Date:                Tue, 19 Apr 2022   Prob (F-statistic):           3.23e-83
Time:                        00:06:08   Log-Likelihood:                -1646.2
No. Observations:                 506   AIC:                             3300.
Df Residuals:                     502   BIC:                             3317.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -21.8728      3.178     -6.883      0.000     -28.117     -15.629
x1             8.4406      0.410     20.563      0.000       7.634       9.247
x2            -0.0994      0.015     -6.582      0.000      -0.129      -0.070
x3            -0.4804      0.200     -2.399      0.017      -0.874      -0.087
==============================================================================
Omnibus:                      177.624   Durbin-Watson:                   0.681
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1270.183
Skew:                           1.340   Prob(JB):                    1.53e-276
Kurtosis:                      10.284   Cond. No.                         851.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""